Algoritmo "semnome"
//Crie um programa que solicite a entrada de 10 números pelo usuário, armazenando-os em um vetor,
//e então monte outro vetor com os valores do primeiro multiplicados por 5. 
// Exiba os valores dos dois vetores na tela, simultaneamente, em duas colunas (um em cada coluna), uma posição por linha
Var
// Seção de Declarações das variáveis 
numero1 : vetor [0..9] de inteiro
numero2 : vetor [0..9] de inteiro
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     para numero de 0 ate 9 faca
   escreval("Digite um número:")
   leia(numero1[numero])
   numero2[numero] <- numero1[numero] * 5
fimpara
escreval()
escreval("Resultado:")
para numero de 0 ate 9 faca
   escreval(numero1[numero], " ", numero2[numero])
fimpara
escreval()

Fimalgoritmo
